### PR TITLE
Alphabetise help string array as per TODO

### PR DESCRIPTION
**Pull request by lycurgus**
Near-trivial practice PR

### CODE REVIEW

**Comment by davidscholberg** [comment]
@lycurgus thanks for the PR!

My only issue with this is that it calls sort for every invocation of the help command. The `helpMsgs` slice only needs to be sorted once.

What I would do is create a function called `SortHelp` in  [lib/module/help.go](https://github.com/davidscholberg/irkbot/blob/97009d256e3bc4093509aec436349d5e85367e97/lib/module/help.go) that simply sorts the `helpMsgs` slice, and then call that function from [lib/module/register.go](https://github.com/davidscholberg/irkbot/blob/97009d256e3bc4093509aec436349d5e85367e97/lib/module/register.go#L99) after all of the calls to `RegisterHelp` have been made.

Let me know if you want to take care of this. If not, I have no problem doing it.

**Comment by lycurgus** [comment]
So I put this together and it seems to work (though it also seemed like the strings were sorted already - but if I purposely reversed the sort that took effect, so I guess it's working?)

Sadly I am bad at git and pushed the change to my master branch instead of the one on this PR... I'm not sure if there's a way to pull the commit in from there to here? or do I need to open a new PR? plz halp

**Comment by davidscholberg** [comment]
@lycurgus here's what I'd recommend:

1. Go to your irkbot checkout and checkout the new sort commit:
    `git checkout 3dfbc961e3b6e66d4cf50f44fe3c4465296383ee`
2. Create a new branch based on that commit:
    `git checkout -b new-sort`
3. Push the new branch to your remote:
    `git push origin new-sort`
4. Update this PR to pull from the `new-sort` branch.

At that point, this PR should only contain the commit with the new sort change (`3dfbc961e3b6e66d4cf50f44fe3c4465296383ee`).

Let me know if you have any questions.

**Comment by lycurgus** [comment]
All of that is done aside from step 4 - I don't seem to be able to change the branch the PR is pulling from. Might just need to can this one and open a new one?

**Comment by davidscholberg** [comment]
For those playing at home, this was solved by force pushing the local `new-sort` branch to the remote`patch-1` branch.

**Pull request merged**
